model = "gpt-5.2-codex"
model_reasoning_effort = "high"

[mcp_servers]
[mcp_servers.MCP_DOCKER]
command = 'docker'
args = ['mcp', 'gateway', 'run']

[mcp_servers.serena]
args = ['--from', 'git+https://github.com/oraios/serena', 'serena', 'start-mcp-server', '--enable-web-dashboard', 'False']
command = 'uvx'

[mcp_servers.taskmaster-ai]
args = ['task-master-ai']
command = 'npx'

[notice]
'hide_gpt-5.1-codex-max_migration_prompt' = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"

[projects]
[projects.'/Users/bob/.claude/skills/zettelmaster']
trust_level = 'trusted'

[projects.'/Users/bob/Downloads/devcontainer']
trust_level = 'trusted'

[projects.'/Users/bob/git/src/github.com/buvis/container-images']
trust_level = 'trusted'

[projects.'/Users/bob/git/src/github.com/doogat/dzs/main']
trust_level = 'trusted'

[projects."/Users/bob"]
trust_level = "trusted"

[projects."/Users/bob/git/src/github.com/doogat/dzs"]
trust_level = "trusted"

[projects."/Users/bob/git/src/github.com/buvis/buvis-pybase"]
trust_level = "trusted"
