GOOSE_MAX_TURNS: 2000
GOOSE_MODE: auto
GOOSE_PROVIDER: openrouter
GOOSE_MODEL: anthropic/claude-opus-4.5
extensions:
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  mcpdocker:
    args:
    - mcp
    - gateway
    - run
    bundled: null
    cmd: docker
    description: The Docker MCP Toolkit allows for easy configuration and consumption of MCP servers from the Docker MCP Catalog
    enabled: true
    env_keys: []
    envs: {}
    name: mcpdocker
    timeout: 300
    type: stdio
