[tools]
node = "latest"
python = "latest"
uv = "latest"
helm = "latest"
rust = "latest"
deno = "latest"
"cargo:rumdl" = "latest"
"uvtool:Yapf" = "latest"
"uvtool:autopep8" = "latest"
"uvtool:beets" = "latest"
"uvtool:buvis-gems" = "latest"
"uvtool:black" = "latest"
"uvtool:gita" = "latest"
"uvtool:llm" = "latest"
"uvtool:pynvim" = "latest"
"uvtool:pybooklid" = "latest"
"uvtool:ruff" = "latest"
"uvtool:yt-dlp" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:@github/copilot" = "latest"
"cargo:zoxide" = "latest"
"uvtool:poetry" = "latest"
"npm:pake-cli" = "latest"
"npm:pnpm" = "latest"

[settings]
experimental = true
