[tools]
node = "latest"
python = "latest"
uv = "latest"
helm = "latest"
rust = "latest"
deno = "latest"
"cargo:rumdl" = "latest"
"uvtool:Yapf" = "latest"
"uvtool:autopep8" = "latest"
"uvtool:beets" = "latest"
"uvtool:black" = "latest"
"uvtool:gita" = "latest"
"uvtool:llm" = "latest"
"uvtool:pynvim" = "latest"
"uvtool:ruff" = "latest"
"uvtool:yt-dlp" = "latest"
"npm:@openai/codex" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:@github/copilot" = "latest"
"cargo:zoxide" = "latest"
"uvtool:poetry" = "latest"

[settings]
experimental = true
